# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCreateNewUser():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCreateNewUser(self):
    self.driver.get("http://127.0.0.1:3000/")
    self.driver.set_window_size(1833, 1030)
    self.driver.find_element(By.LINK_TEXT, "Open Admin UI").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dashboard-group:nth-child(4) .dashboard-group__list-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-we21er").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-we21er")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "52r25dqb3").send_keys("test")
    self.driver.find_element(By.NAME, "name.last").send_keys("CreateNewUser")
    self.driver.find_element(By.ID, "49v9szsyf").click()
    self.driver.find_element(By.ID, "49v9szsyf").send_keys("newuser@keystonejs@")
    self.driver.find_element(By.ID, "49v9szsyf").send_keys("newuser@keystonejs.com")
    self.driver.find_element(By.ID, "3lufmk7q3").click()
    self.driver.find_element(By.ID, "3lufmk7q3").send_keys("newusertest1")
    self.driver.find_element(By.NAME, "password_confirm").click()
    self.driver.find_element(By.NAME, "password_confirm").send_keys("newusertest1")
    self.driver.find_element(By.CSS_SELECTOR, ".css-h629qq").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-h629qq")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
  
