# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCreateNewPost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCreateNewPost(self):
    self.driver.get("http://127.0.0.1:3000/")
    self.driver.set_window_size(1833, 1030)
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    self.driver.find_element(By.ID, "1u8wop6pg").click()
    self.driver.find_element(By.ID, "1u8wop6pg").send_keys("demo@keystonejs.com")
    self.driver.find_element(By.ID, "m9l8eu4xq").click()
    self.driver.find_element(By.ID, "m9l8eu4xq").send_keys("demo")
    self.driver.find_element(By.CSS_SELECTOR, ".css-2960tt").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dashboard-group:nth-child(1) .dashboard-group__list:nth-child(1) .dashboard-group__list-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-we21er > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-we21er > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "yn2vwd3tf").send_keys("testCreateNewPost")
    self.driver.find_element(By.CSS_SELECTOR, ".css-h629qq").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-h629qq")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#mceu_2 > button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
  
